Convert PrePrepareMsg to smart pointer
glevkovich/concord-bft pull request #78
Opened 2023-01-15 19:16 UTC by Efrat1

Convert PrePrepareMsg raw pointer to smart in:
- ReplicaImp::onMessage<PrePrepareMsg>()
- startConsensusProcess().

Tested: Apollo, maestro, ASAN

2023-01-17 14:02 UTC, glevkovich requested changes

2023-01-17 14:02 UTC, glevkovich commented on bftengine/src/bftengine/ReplicaImp.cpp
> +  auto ppMsg = seqNumInfo.getPrePrepareMsg();
1) nit:
Why do you need to call to another object to get a pointer which you already have? that looks a bit strange to me. how about:
```
 SeqNumInfo &seqNumInfo = mainLog->get(primaryLastUsedSeqNum);
auto ppMsg = pp.get();
  {
    TimeRecorder scoped_timer1(*histograms_.addSelfMsgPrePrepare);
    seqNumInfo.addSelfMsg(std::move(pp));
  }

if (ps_) { ...
```

2)
Do we have a task to convert seqNumInfo and possibly mainLog into a smart pointer?
getPrePrepareMsg returns a raw pointer - how much effort to add this into your task? I think too much?
If yes, lets open a task.

2023-01-17 14:02 UTC, glevkovich commented on bftengine/src/bftengine/ReplicaImp.cpp
> +    if (viewsManager->addPotentiallyMissingPP(message.release(), lastStableSeqNum)) {
1) 
This is a leak. You can't release before you got the answer from addPotentiallyMissingPP.
If addPotentiallyMissingPP returns false you must keep ownership:
```
if (viewsManager->addPotentiallyMissingPP(message.get(), lastStableSeqNum)) {
  message.release(); 
   ...
```

2) Do we have a task to convert views manager (all functions, or at lease this one, depends on its size) to smart pointers?

2023-01-17 14:02 UTC, glevkovich commented on bftengine/src/bftengine/ReplicaImp.cpp
> +    if (seqNumInfo.addMsg(std::move(message), false, time_is_ok)) {
```
auto ppMsg = message.get();
if (seqNumInfo.addMsg(std::move(message), false, time_is_ok)) {
```

and then use ppMsg and avoid calling  seqNumInfo.getPrePrepareMsg(); in line 1121 and 1139.

2023-01-17 14:02 UTC, glevkovich commented on bftengine/src/bftengine/ReplicaImp.cpp
> +      return startConsensusProcess(PrePrepareMsgUPtr(*ppm), true);
nit: use make_unique, it is the recommended way vs uptr ctor.

2023-01-17 14:02 UTC, glevkovich commented on bftengine/src/bftengine/ReplicaImp.cpp
> +      seqNumInfo.addSelfMsg(std::make_unique<PrePrepareMsg>(pp));
This looks not right.
It all starts from the fact that we pass into this function a vector with raw pointers. If the vector was with a smart pointer, why would you need to create a new smart poiunter here and not just move an existing one?

So this code and all the later parts which create unique_ptr looks artificial ("half work"? )
now, if you hve future tasks it's fine, although thye must be documented very well.
But I assume you dont.
Start from passing 
`const std::vector<PrePrepareMsgUptr> &prePreparesForNewView`

and if you dont want to do it here, open a new task. But this code should just move the pointer in prePreparesForNewView and not create a raw pointer.
same for all below code till function end.

2023-01-17 14:02 UTC, glevkovich commented on bftengine/src/bftengine/SeqNumInfo.cpp
> +  outPrePrepare = prePrepareMsg.release();
Strange function definition style. That's how C is written, not modern C++.
I suggest to transform (consider if you like in another task):
`std::pair<PrePrepareMsg*, PrepareFullMsg*>  SeqNumInfo::getAndReset()`

caller can just call:
`auto [ ppMsg, ppFMsg ] = seqNumInfo::getAndReset();`

2023-01-18 17:22 UTC, Efrat1 commented on bftengine/src/bftengine/ReplicaImp.cpp
> +  auto ppMsg = seqNumInfo.getPrePrepareMsg();
1. Changed, thanks.
2. PrePrepareMsg in SeqNumInfo is already a unique_ptr, and SeqNumInfo is the owner of it. getPrePrepareMsg and getSelfPrePrepareMsg return raw pointer as they are used to read only.
I created a task for other raw pointers in SeqNumInfo: [BC-26948](https://jira.eng.vmware.com/browse/BC-26948)

2023-01-18 17:22 UTC, Efrat1 commented on bftengine/src/bftengine/ReplicaImp.cpp
> +    if (viewsManager->addPotentiallyMissingPP(message.release(), lastStableSeqNum)) {
1. Thanks, fixed.
2. Yes, [BC-26902](https://jira.eng.vmware.com/browse/BC-26902)

2023-01-18 17:22 UTC, Efrat1 commented on bftengine/src/bftengine/ReplicaImp.cpp
> +    if (seqNumInfo.addMsg(std::move(message), false, time_is_ok)) {
Done

2023-01-18 17:22 UTC, Efrat1 commented on bftengine/src/bftengine/ReplicaImp.cpp
> +      return startConsensusProcess(PrePrepareMsgUPtr(*ppm), true);
Done, thanks.

2023-01-18 17:22 UTC, Efrat1 commented on bftengine/src/bftengine/ReplicaImp.cpp
> +      seqNumInfo.addSelfMsg(std::make_unique<PrePrepareMsg>(pp));
I agree.
The vector of raw pointers (prePreparesForNewView) came from ViewManager which holds only raw pointers.
I did open a task for ViewManager ([BC-26902](https://jira.eng.vmware.com/browse/BC-26902)). However, I edited its description to be more explicit.

2023-01-18 17:22 UTC, Efrat1 commented on bftengine/src/bftengine/SeqNumInfo.cpp
> +  outPrePrepare = prePrepareMsg.release();
Changed, thanks.

2023-01-19 16:50 UTC, glevkovich approved these changes
LGTM, thanks for the hard work!

2023-01-19 16:51 UTC, merged